"""empty message

Revision ID: 43b95fc116a3
Revises: f690c4a1ae2b
Create Date: 2018-03-10 14:32:44.292996

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43b95fc116a3'
down_revision = 'f690c4a1ae2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('productivity_factor', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'productivity_factors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks',
                  sa.Column('productivity_factors', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
                            autoincrement=False, nullable=True))
    op.drop_column('tasks', 'productivity_factor')
    # ### end Alembic commands ###
