"""empty message

Revision ID: 673bc9fdac42
Revises: 
Create Date: 2018-02-24 13:55:42.226687

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '673bc9fdac42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifiers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('duration_p', sa.JSON(), nullable=True),
                    sa.Column('scattering_q', sa.JSON(), nullable=True),
                    sa.Column('dispersion_h', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('size_p', sa.String(), nullable=True),
                    sa.Column('size_q', sa.String(), nullable=True),
                    sa.Column('size_h', sa.String(), nullable=True),
                    sa.Column('classifier_id', sa.Integer(), nullable=True),
                    sa.Column('type_device', sa.String(), nullable=True),
                    sa.Column('tasks_count', sa.Integer(), nullable=True),
                    sa.Column('criterion_device', sa.String(), nullable=True),
                    sa.Column('distribution', sa.String(), nullable=True),
                    sa.Column('algorithm_generation', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['classifier_id'], ['classifiers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('set_id', sa.Integer(), nullable=True),
                    sa.Column('productivity_factors', sa.ARRAY(sa.Float()), nullable=True),
                    sa.Column('devises_amount', sa.Integer(), nullable=True),
                    sa.Column('tasks_amount', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('sets')
    op.drop_table('classifiers')
    # ### end Alembic commands ###
