"""empty message

Revision ID: f690c4a1ae2b
Revises: 673bc9fdac42
Create Date: 2018-03-10 14:25:58.731008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f690c4a1ae2b'
down_revision = '673bc9fdac42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tasks', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'tasks_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tasks_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'tasks')
    # ### end Alembic commands ###
